Remove wrong characters from environment file
SUSE/caasp-openstack-heat-templates pull request #7
Opened 2018-07-20 07:28 UTC by mjura

2018-07-20 14:20 UTC, kiall requested changes
Looking at the YAML, it's still not 100% right - everything appears to be indented 1 character

2018-07-24 17:05 UTC, mjura commented
@kiall: It must github, I've checked this on my dev environment and even RAW change
https://raw.githubusercontent.com/mjura/caasp-openstack-heat-templates/6aa3e0f16212d79b773d75ea4bea1a129affa2fb/caasp-environment.yaml
It looks OK

2018-07-26 12:49 UTC, sayalilunkad commented on caasp-environment.yaml
> ----
This just needs to be replace with 3 --- to indicate the start which is optional of course so I don't mind either way.

2018-10-25 09:12 UTC, sayalilunkad approved these changes

2018-10-30 08:13 UTC, merged